I see a syntax error in the Python code that's being imported. The error is occurring because 'async' is being used as a variable name, which is a reserved keyword in Python. Let me examine the experiment.py file to fix this issue.
The error is not in experiment.py directly, but in one of its dependencies. Specifically, the error is in the pypdevs library at /Users/likhithkanigolla/IIITH/MS/S1-Course/IS/CAPS-IIITH/venv-3.11/lib/python3.11/site-packages/pypdevs/controller.py, line 551, where it's using 'async' as a variable name. This is a syntax error because 'async' is a reserved keyword in Python.

Since this is a library issue in the virtual environment, we have two options:
1. Install an older version of pypdevs that's compatible with your Python version
2. Create a patch for the library in your virtual environment

Let me check the installed version of pypdevs first.
I see that you're using PyPDEVS version 2.4.1. The issue is that this version of the library was written before 'async' became a reserved keyword in Python (which happened in Python 3.7). Let me help you fix this by modifying the controller.py file in your virtual environment.

Let me make a backup of the original file first and then modify it to use a different variable name instead of 'async'.
I need to fix a syntax error in the pypdevs library file. The issue is on line 551 of the controller.py file, where the code is using 'async' as a variable name. Since 'async' became a reserved keyword in Python 3.7+, this is causing a syntax error.

I'll create a diff to modify this file and rename the variable from 'async' to 'async_gen' to fix the syntax error.